[build]
  command = "npm run deploy"
  publish = "dist/demo"

[functions]
  directory = "dist/server"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200